### ISSUE TITLE
Missing expansions for certain resources' attributes' valid codes

### ISSUE THREAD

**Issue by asross** [fhir-crucible/fhir_models#3]
It looks like a few value sets are missing from `definitions/valuesets/expansions.json`, which is throwing the following console output when we require `fhir_models`:

![image](https://cloud.githubusercontent.com/assets/1022564/15025448/4441da62-1207-11e6-907e-9d4a396c6f73.png)

We tried looking up a few of them by their URIs, and actually encountered errors on the main FHIR site when looking for them, so it might be a bug in FHIR itself, but it does seem like an issue worth fixing. We're thinking of silencing the console output but we're not sure if that's the right thing to do.

**Comment by jawalonoski** [comment]
We have plans to fix this... hasn't been a huge priority leading up to the May Connectathon. We'll need to resolve these though so that we can properly generate the effected resources.

**Comment by jawalonoski** [comment]
Any remaining missing expansions (now silenced in the output) are not `required` bindings -- which means that they are not technically required for validation.
