### ISSUE TITLE
Profile Validation doesn't validate as hierarchy

### ISSUE THREAD

**Issue by dehall** [fhir-crucible/fhir_models#38]
The profile validation logic (starting from `StructureDefinition.validate_resource` ) doesn't validate the FHIR resources as a hierarchy.

As an example, consider the US Core Patient profile:  https://hl7.org/fhir/us/core/StructureDefinition-us-core-patient.html  
This profile specifies that a Patient may have 1..* `Identifier`s, and each Identifier must have 1..1 `value`.  The profile is represented in JSON with a flat list of elements, so "Patient.Identifier.value" is an element of the list, with cardinality 1..1.
Because the validation process loops over each element individually, when it tries to validate the "Patient.Identifier.value" element it will pull out all nodes from the entire JSON matching path "Patient.Identifier.value" which could be many, if the Patient has many Identifiers. Then the validation can fail because it expects value to have cardinality 1..1 but found many.
(Note that as of right now this example will actually pass, because it will only take the first Identifier of many; I think this is a separate bug and the highlighted line should be pulled out of this loop:  https://github.com/fhir-crucible/fhir_models/blob/v1.8.3/lib/fhir_models/fhir_ext/structure_definition.rb#L95  . I found the issue with a more complicated profile where it does fail, this is the best example I see in the core) 

One possible change would be to only verify elements within the context of their parent element.
Ex, change `verify_element` to take path as a parameter:

```
def verify_element(element, json, path)
```

then at the end when it loops over children, validate each child only in the context of the nodes for this element path. In other words, only pass `node` to the call to `verify_element` instead of passing the entire json
```
      # check children if the element has any
      return unless element.children
      element.children.each do |child|
        nodes.each do |node|
          child_path = child.path
          current_path = element.path
          # .. strip current_path, plus 1 '.' from the start of child_path
          verify_element(child, node, child_path)
        end
      end
```

That said I'm not sure if this approach would break anything else.  I tested it locally and all unit tests pass but I know that doesn't mean it's right.

**Comment by jawalonoski** [comment]
The title of this issue is a little misleading... or confusing.

The code does validate as a hierarchy. See the changes to [ElementDefinition](https://github.com/fhir-crucible/fhir_models/blob/master/lib/fhir_models/fhir_ext/element_definition.rb) -- in particular `@children` and the `build_hierarchy` method in the file you linked to that gets called before validation begins.

You could argue that `get_json_nodes` or `verify_element` has a bug. The best way to do that would be provide an example that doesn't work correctly.

Can you provide an example (profile and resource) that fails?

**Comment by dehall** [comment]
I would argue it's not validated in a hierarchical way, because validating each element is done in the context of the entire JSON object, instead of validating each element in the context of its direct parent. Maybe it's just semantics.

The simplest example of incorrect behavior is a case where validation passes, but it should fail.
The US Core Patient profile requires 1..* `Identifier`s, and each Identifier to have 1..1 `value`. The bug in `get_json_nodes` means that as long as the first Identifier is completely valid, every element under Identifier passes even if the other Identifiers are not valid.

In the test fixture `sample_us_core_record.json` , delete the `value` field from the 2nd or 3rd `identifier` object. (starting at line 84) Or, attached here: [sample-us-core-record.json.txt](https://github.com/fhir-crucible/fhir_models/files/937124/sample-us-core-record.json.txt) Because value is 1..1, the record no longer adheres to the US Core Patient profile. Test case `ProfileValidationTest.test_profile_validation_resource` already validates this patient record against that profile, so just run that test. The test case expects the record to adhere to the profile, but with the changes we now expect it to fail. It still passes after deleting the required value field, so something is wrong.

If we then change `get_json_nodes` to move the return statement out of the loop:
```
json.each do |e|
  results << get_json_nodes(e, steps[index..-1].join('.'))
end
return results.flatten!
```
Things still aren't correct. Now running the ProfileValidationTest suite results in a ton of cardinality errors (if you change the `assert errors.empty` calls to `assert_empty errors` it's easier to see)

From the results of the `test_profile_validation` test:
   "Observation.component.code failed cardinality test (1..1) -- found 2",
   "Observation.component.valueQuantity failed cardinality test (0..1) -- found 2",
   "Observation.component.valueQuantity.value failed cardinality test (1..1) -- found 2",
   "Observation.component.valueQuantity.unit failed cardinality test (1..1) -- found 2",
   "Observation.component.valueQuantity.system failed cardinality test (1..1) -- found 2",
   "Observation.component.valueQuantity.code failed cardinality test (1..1) -- found 2",
(repeated ~60 times, because this is the cumulative result of calling `profile.validate_resource` on each individual entry in a bundle)
The sample really is valid, but since each `Observation` (for Blood Pressure) has 2 `component`s, each with 1 `code`, those are getting lumped together as 2 "Observation.component.code"s instead of 2 components with 1 code each.

I think the only way to solve that is to validate all the objects individually by only looking at 1 object and its children at a time instead of the whole JSON at a time. I.e., the change I suggested above. But I'm very unsure about the implementation, hence this being an Issue instead of a PR.
