### ISSUE TITLE
Validation fails on contained resources

### ISSUE THREAD

**Issue by BillyYarosh-WellSky** [fhir-crucible/fhir_models#75]
When building a `FHIR::MedicationRequest`, you can include the medication in the `contained` section. In this case, the `medicationReference` is a relatively linked resource. Validation fails in this case.

Example:

```ruby
puts FHIR::MedicationRequest.new(
  medicationReference: 
    FHIR::Reference.new(
      reference: "#medication-1234",
      display: 'Med Name',
      type: 'Medication'
    ),
  contained: [FHIR::Medication.new]
).validate
```

This outputs the error:
```
"medicationReference"=>["MedicationRequest.medication[x]: incorrect Reference type, expected Medication"]
```

In the case of medicationReference, you should be able to specify a reference URL this is a hash tag.
More info here: http://hl7.org/fhir/STU3/references.html#contained

**Comment by arscan** [comment]
I'm not sure if this will make a difference, but the I believe the contained resource should be `FHIR::Medication.new(id: 'medication-1234')`.  Does that help?

**Comment by BillyYarosh-WellSky** [comment]
Sorry, I didn't supply a fully built resource but just enough to exercise the issue. Yes, if I add an ID (and in that format), the issue persists.

**Comment by BillyYarosh-WellSky** [comment]
Ah yes, the ID is required in the contained medication. The specific issue was that my ID was an integer type so when the library checks equality it fails because `1234 != '1234'`.
