### ISSUE TITLE
STU3 & DSTU2 FHIR resources support

### ISSUE THREAD

**Issue by sivagollapalli** [fhir-crucible/fhir_models#90]
Currently, as per README this gem supports only R4 standard. Any plans to support stu3 & dstu2 standard support.

**Comment by arscan** [comment]
Hi @sivagollapalli -- see https://github.com/fhir-crucible/fhir_stu3_models/ and https://github.com/fhir-crucible/fhir_dstu2_models/ for support for those versions of FHIR.  Those gems put the classes in `FHIR::STU3` and `FHIR::DSTU2` modules, so you can load them in the same application as R4 models if you need to.

**Comment by sivagollapalli** [comment]
@arscan  Sorry I didn't verify.  Thanks for response.
